# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: planethouki
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: lambda-learn
service: lambda-learn

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.11
  region: ap-northeast-1 # 東京リージョン
  environment:
    SYMBOL_PRIVATE_KEY: ${env:SYMBOL_PRIVATE_KEY, ''}
    SYMBOL_NODE_URL: ${env:SYMBOL_NODE_URL, ''}
    SYMBOL_RECIPIENT_ADDRESS: ${env:SYMBOL_RECIPIENT_ADDRESS, ''}
    SYMBOL_MOSAIC_ID: ${env:SYMBOL_MOSAIC_ID, ''}

functions:
  hello:
    handler: functions/hello.handler
    description: 'Hello関数'

  hoge:
    handler: functions/hoge.handler
    description: 'Hoge関数'

  fuga:
    handler: functions/fuga.handler
    description: 'Fuga関数'

package:
  individually: true
  patterns:
    - '!node_modules/**'
    - '!.gitignore'
    - '!.git/**'
    - '!package.json'
    - '!package-lock.json'
    - '!README.md'

custom:
  pythonRequirements:
    dockerizePip: false  # Dockerを使用しない場合はfalse
    zip: true
    slim: true  # 不要なファイルを除外してパッケージサイズを削減
